[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
maxThreads = 4

[browser]
gatherUsageStats = false

[global]
developmentMode = false
dataCaching = true